
version: '3.8'

services:
  docker-agent:
    image: docker:dind
    depends_on:
      - jenkins-mt
    restart: unless-stopped
    privileged: true
    command: --storage-driver=overlay2
    networks:
      jenkins:
         aliases:
            - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./vols/jenkins-docker-certs:/certs/client
      - ./vols/jenkins-data:/var/jenkins_home
    ports:
      - '2376:2376'

  jenkins-mt:
    image: jenkins-blueocean
  #  privileged: true
  #  user: root
  #  container_name: jenkins
    build:
      context: ./jenkins-mt
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8088:8088'
      - '50000:50000'
    user: jenkins:jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - ./vols/jenkins-data:/var/jenkins_home
      - ./vols/jenkins-docker-certs:/certs/client:ro
      - ./jenkins-mt/jenkins-config.yml:/var/casc_configs/jenkins-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge